version: "3"
services: 
    app:
        build: 
            context: .

            # dockerfile: Dockerfile.create
            # then docker-compose exec app sh >> cd ../ >> vue create vue_app

            # dockerfile: Dockerfile.dev
            dockerfile: Dockerfile.build

        ports: 
            - "8080:8080"
            - "80:80"
        volumes: 
            - ./codekids-class:/home/codekids-class
            - /home/codekids-class/node_modules
        environment: 
            - CHOKIDAR_USEPOLLING=true